### ISSUE TITLE
Include export templates

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.godotengine.Godot#1]
It'd be good to include the X11 x86 32 and 64 bit export templates as otherwise the user has to visit a webpage and download a 200mb ZIP file which is a bit less cool.

Instructions are at:
http://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html#building-export-templates

**Comment by TingPing** [comment]
Maybe they should be extensions if they are that large.

**Comment by TingPing** [comment]
We do include a 64bit linux export template but we need to document somewhere how to use it because they really can only run inside of `flatpak` since it links against host libs.

**Comment by Calinou** [comment]
Godot 3.0 onwards features an export template manager, which can download export templates and install them automatically. After some discussion on the `#flatpak` IRC, it seems we should rely on that instead of bundling export templates (which not everyone needs if they're just starting out with Godot).
