### ISSUE TITLE
Cannot use text-to-speech due to missing speech-dispatcher dependencies

### ISSUE THREAD

**Issue by Calinou** [flathub/org.godotengine.Godot#122]
Running the Godot Flatpak prints an error about libspeechd missing (despite it being installed on my system):

```
❯ flatpak run org.godotengine.Godot           
Godot Engine v4.0.1.stable.flathub.cacf49999 - https://godotengine.org
libspeechd.so.2: cannot open shared object file: No such file or directory
```

This most likely prevents [text-to-speech](https://github.com/godotengine/godot-demo-projects/tree/master/audio/text_to_speech) from working.

**Comment by Zishan-Rahman** [comment]
I know it's been 3 months since this issue was opened, but would it be worth considering building libspeechd as either a module in here or a shared module in [flathub/shared-modules](https://github.com/flathub/shared-modules)? I'm also having the same problem (on Linux Mint 21), and it does indeed stop the text-to-speech demo project from working as it should on my computer.

**Comment by Calinou** [comment]
shared-modules mentions this requirement for adding modules to it:

> Please do not request adding modules unless they have many users in the Flathub repository.

I think it's better to build libspeechd in this Flatpak for now.

**Comment by hypevhs** [comment]
@Zishan-Rahman Feel free to adapt the libspeechd module from flathub/org.electronjs.Electron2.BaseApp#59 to fit Godot's use cases.
