### ISSUE TITLE
"flatpak update" doesn't update to 3.4

### ISSUE THREAD

**Issue by Butzwack** [flathub/org.godotengine.Godot#91]
`flatpak update` returns `Nothing to do.`, please correct me if this is intended and 3.4 is held back until the release blog post is ready.
https://flathub.org/apps/details/org.godotengine.Godot also displays 3.3.4 as the current version.
Looking through previous version bumps I found that they usually change org.godotengine.Godot.yaml & org.godotengine.Godot.appdata.xml but cbe26ce only touched org.godotengine.Godot.yaml, so maybe that's the issue.

**Comment by Calinou** [comment]
The 3.4 build is completed on the Flathub buildbot, but it's not published yet: https://flathub.org/builds/#/builders/32/builds/66208

By default, builds have a 2-hour delay before being published so that developers can test them and ensure they're working. Nonetheless, I just force-published the build so it's available immediately.
